parameters:
#    events.example.class: Kinash\EventsBundle\Example

services:
#    events.example:
#        class: %events.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
